services:
  api:
    container_name: sociolegal_api
    build: .
    ports:
      - 8082:8000
    env_file: 
      - .env
    environment:
      DB_CONNECTION : ${DB_CONNECTION}
      MONGO_HOST : ${MONGO_HOST} 
      MONGO_PORT : ${MONGO_PORT}
      MONGO_DB : ${MONGO_DB}
      MONGO_USER : ${MONGO_USER}
      MONGO_PASS : ${MONGO_PASS}
    depends_on:
      - db    
  db:
    container_name: sociolegal_bd
    image: mongo:4.2
    env_file: 
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - 27019:27017
    volumes:
      - ./bambi_socio_legal-data/mongo/:/data/db 
  
volumes:
  bambi_socio_legal:

    